---

nut_host: localhost

nut_mode: netserver

nut_user_mode: master

nut_ups_devices:
  - name: cyberpower
    usb_vendor_id: "0764"
    usb_product_id: "0601"
    config: |
      driver = usbhid-ups
      port = auto
      ignorelb
      pollinterval = 5
      override.battery.runtime.low = 480
      offdelay = 120

nut_ups_listen: |
  LISTEN 127.0.0.1 3493
  LISTEN {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} 3493
  LISTEN ::1 3493
