---

- name: Set Docker container parameters
  set_fact:
    piwigo_container_parameters:
      name: "{{ piwigo_name }}"
      hostname: "{{ piwigo_name }}"
      image: "{{ piwigo_image }}"
      state: started
      published_ports: "{{ piwigo_ports }}"
      env: "{{ piwigo_environment_variables }}"
      volumes: "{{ piwigo_volumes }}"

- name: Create Piwigo container
  docker_container: "{{ piwigo_container_parameters | combine(piwigo_docker_additional_options) }}"
  register: piwigo_container
