---

common_user: calvin
common_group: calvin
common_user_id: "1000"  # calvin
common_group_id: "1000"  # calvin
common_root_id: "0"  # root
common_root_group: "0"  # root
common_timezone: "Australia/Sydney"
common_directory: "/apps"
common_tld: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62346335393434623031643738616235643136343138623639353663323161396366333463666334
  3537343762653765636464363166633035386432313533390a376537373164366530653164343763
  65343162356233303266616631323064323238353561653736363732623966363932616530633433
  3135623464636636350a656564653563616230653365373032663038346132343531666637636663
  3837
common_local_tld: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63613961636466383733373937333935346661626534633537306664633430643937366334333764
  3239656237316365613763356564326335633633383165300a376263613730393562383534373563
  66653763343931313534663638306565643132646663343635663735323639346530633132316365
  6431363834356634650a336233363230313137393934346364333835376333346432303962313533
  6263
common_language_iso_639: "en"
common_country_iso_3166: "AU"
common_locale: "{{ common_language_iso_639 }}-{{ common_country_iso_3166 }}"
