---

# ‚ùØ htpasswd -n blackbox_exporter
# New password:
# Re-type new password:
# blackbox_exporter:$xxxxxxxxxxxxxxxxx

# for autodiscovery
htpasswd:
  username: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    39663236383764373738663332326630613566323262613130616334623838396435363563343332
    6335613332613335386362653433653735346436656539360a363535636230303536613737356165
    33306238386465396666643139613261333532663836393761613134353537653036326632356233
    3337333535353137660a326265343664353631323835333162373161613438633337363762373537
    6534
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    65313935633931623464356235613533653265376234356234626461336563323861363834353636
    3035316331633233303562306137613266386463383735340a333334373337353138303863353231
    36663565333935353736633732623537633832306639656362353430613135663437376165666332
    3163636464646133300a316530353533613538323962633963646239353330396538646236343161
    39346537336339633237633362656263373932663663366236613962656564353065
  password_hashed: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    64373538363034653439623030626136663437656466393662383939326235626432343734616431
    3132376365373436666435613466633433396539323537640a626432316262363831323262663030
    31646635353237386461376165313337336163393631663533373637373434643339623431336435
    3562626565316262310a656635333964653762303731346561663438363231613035333964633364
    33653334666662303836653136333161376137656264313466343838366361356136373861383738
    3635386532373865393264376264373532356632383739313233
  password_hashed_bcrypt: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    33646636356164363966633763396265663166646434613866366532393065306337373137666130
    3230653662336435653964626139376630316166656538350a343233353639643735643731623365
    35393537653034303833383239333734636431646264623366363338626661323130326430613531
    6231623835383937320a313438386536313630656163323966306536343235323965663665363230
    30373632373866303366303466383331366234343330613465303534613835386633383136316432
    64353966393933356332333030323435343363396137343236656234316533613237663031343662
    343438326637626162373963396665623836

blackbox_htpasswd:
  username: "blackbox_exporter"
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34383333643137383131626362303631666661316266643464353433656566656564376362376539
    3866303566616666366639366430336461386338393137640a653431326162663534383262363361
    37323562613937393132326136643134626330626133643263386532363830663932323134353732
    6264313134343138340a653564386132393864326436323638393137633261353564643433623739
    63313961636137316632646334363330613539333163663862643539376361346232313166613765
    32623466656336623738343739353937613263316630303936643137306435306464393563643937
    653834333934626436633839663166646237
  password_hashed: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    33313163636436393861346535653939623230363965626231346566663537613331613530633066
    3438366363373631323935313362383138626639393737640a363161616334646437343532393962
    36633632633835323334383261663839303937303632613665633330616437373736653564336166
    3964643738313633360a643966323732343865303437373062636235666137376465393530646638
    64623136363161313633393364376665343061373863646362366635383331366633326635323066
    6139663239363038326233353564303366636139623132313537
