---

oidc_provider: authelia

oidc_base_url: "https://{{ oidc_provider }}.{{ common_tld }}"
oidc_discovery_url: "{{ oidc_base_url }}/.well-known/openid-configuration"
oidc_auth_url: "{{ oidc_base_url }}/api/oidc/authorization"
oidc_token_url: "{{ oidc_base_url }}/api/oidc/token"
oidc_userinfo_url: "{{ oidc_base_url }}/api/oidc/userinfo"
oidc_signout_url: "{{ oidc_base_url }}/application/o/{{ application }}/end-session/"
oidc_jwks_url: "{{ oidc_base_url }}/jwks.json"


# run `authelia crypto hash generate pbkdf2 --variant sha512 --random --random.length 72 --random.charset rfc3986 | grep 'Random'`
oidc_auth:
  audiobookshelf:
    redirect_uris:
      - "https://audiobookshelf.{{ common_tld }}/auth/openid/callback"
      - "https://audiobookshelf.{{ common_tld }}/auth/openid/mobile-redirect"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30633665303438396531386662383961313837646535336433303230393239636635376530343962
      6331616662646561663738663566366236626438393239320a396464396534663532313538643430
      37656634646538336434316539333161663661366237623739393031666361396433383533636532
      3064333730663232370a383166356237333632633733333036303764616335363837643636643336
      63343032383764326530363433663237613037623263333234373636303033393233366433343861
      36666163663036356436303630643934636335633431646433623931303337326666346664366130
      64623436346134666533653738383538353230303964346432316365383633383964623933656363
      31336364316638383065

  filebrowser:
    redirect_uris:
      - "https://filebrowser.{{ common_tld }}/api/auth/oidc/callback"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34363536326664383561363763663531333934633035393530373864656435363234643437323136
      3238393866366635383133393331386563643332343565370a666533663034636130333436613063
      35323362383635616534643463353061303132623864633935343565386635646664643834613632
      6331613334663639330a623138653736316130343637393030636139646633336332343431313164
      34656563636631343334333737653563333066653863653761393635376333363638343431366664
      66323765626539363766333263333731393564343435333536313433623536353130623333323735
      61366466646264633732356239336137613838313362366163326630653536666439306263653564
      36346634343034393539

  forgejo:
    redirect_uris:
      - "https://forgejo.{{ common_tld }}/user/oauth2/Authelia/callback"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      30303831623566303732326438313163653432366365326261663235313866326666373139663665
      6633376135373763333565343064643265643865396537660a326263373737653535396362386430
      34343432323739653930623765363036346433393932643265333134346465333163363162303439
      3665666265313361310a636632653164366438323137343836363838323061613538336638653035
      35366634663365633165393365633430343965633333353238653637323064666634346138653262
      34336463316339316237656431346332326634303735653031376239623166626463633931363762
      38646134386533386364613964323466623732323632363465646434316461383836346232373164
      61386635636236326130

  grafana:
    redirect_uris:
      - "https://grafana.{{ common_tld }}/login/generic_oauth"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61393861616262326339346430646137636161353764643664396564663264336335366238326131
      3065323561613761346365303664303837626134616231360a636566363532343361643535643432
      37633238616662386661643666393032393563613563316436636431313763646265356363643031
      3432376131626334340a323234656536303835366536363339656532306261376633633332623630
      33636232306161303934613936666534353265646537613161633538633465363166363534346332
      36353930316432386430396564343530666237643732393631623630643131323261633465346431
      39373734376361393433646139363262346564636534373633343331353731343537326562396162
      39616137376632376435

  immich:
    redirect_uris:
      - "app.immich:///oauth-callback"
      - "https://immich.{{ common_tld }}/auth/login"
      - "https://immich.{{ common_tld }}/user-settings"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65663837383435333963363333626364653864653835383165313733336133363061343765376137
      3234363065626166326134636532653961343737326661660a376538353963333036373265303637
      37363539666439653430633865376437646530643962626533376664656431656532623539313434
      3030323133383166360a363866313162363833613335653136333061303632356534353535633662
      63303763633939376163616662393866396262333862653237343132396134353731623735616335
      33353366616139333037313638613435326436333763366364303239366362363064623933303366
      32306531376562363338623338316465383661343532653937353032663861393762366665356339
      62393936363363313537

  karakeep:
    redirect_uris:
      - "https://karakeep.{{ common_tld }}/api/auth/callback/custom"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36303061356438373764653132653636393064656466373935386435633838346136393932656236
      3538653138393131316461373131653836316666373961640a306162643134396537343534393638
      38343065303435643830633363663366353962383630616636316638353033656664646165313264
      6261636436626436330a653533636661326634666661613762373233313231633161356563323336
      35616333346432373132303562613931383637343263616330366135643965306434653366383535
      39346661333434396463646433613130326433396530343332643766383633616636653831343537
      38633338633531616237616336303032373033636662656562323761386161666438306136646132
      62313862333433393732

  librechat:
    redirect_uris:
      - "https://librechat.{{ common_tld }}/oauth/openid/callback"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      31653963383566306437666164346137346463616130633632373132323638633663363239623438
      3038316232373434346133636561663739316337633065650a306436656132616365663334663361
      38323761323635356533396265633966396130363737633565616636616134623232336436343636
      3663363838373434370a653135363636373438326162616137373065353237646536656132663638
      34636232643036326432366630376233633138393930393831616230346462323337303832666362
      64653762636633323531306361303631373631663966663536303932643862393233616265346365
      34306165333234323637353034393034313530663837626237636363313838343137613039653533
      65386639356361343533

  lubelogger:
    redirect_uris:
      - "https://lubelogger.{{ common_tld }}/Login/RemoteAuth"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      65623838343263613363633037663764396233663361376634353766303963323137333230316534
      3933373534306661613537346161353036646439333066310a666633383961366234636238393763
      31616365636563393030343232303437383665633764663536376639653563613234343832313334
      3231663931393565340a316534373134356330623537303561353935616537303832306139396665
      66366437353361313961393836336165386365633463343862666262373531393866363865323832
      33303431646636613565383734366366323930353866316564396130326238333034313834633232
      61333035613631323638373930343063323862323435343365373232356332623938376435356236
      36633938663234636362

  manyfold:
    redirect_uris:
      - "https://manyfold.{{ common_tld }}/users/auth/openid_connect/callback"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37383462336632396632323461663638636235636636633538386562373562613162353138383066
      6562613330613033626231393337386161393737346665300a636261386664633563353431343834
      66303231366461346232386531386235346361376133393433316562646163346232643737323264
      6266393433636134350a383731613833653766666563353838323334663433363834646661383135
      35616634356132333961306539633730363634613564353332343633313032396163373133393663
      66323238326232616562326366666437373961666234626331376431636663626538356635356265
      36373466303936336131326136353335313037643736613537396163646531373566333530633930
      38636636323838356638

  mealie:
    redirect_uris:
      - "https://mealie.{{ common_tld }}/login"
      - "https://mealie.{{ common_tld }}/login?direct=1"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35376332626332666431643134623163646634646662633231396462376234623563336136303631
      3534316163633961646661663163656261656630353033320a633233623064633938626361633938
      32393666333664663637383931316139663536356136643662313761623530323334346464323130
      3834653037333034370a316565353631633965306239656536366365363930353234326130313961
      39393730346635393630363363363463613530313139383435613030623236343061376236356563
      33613633303666326563386234613438323631373339396163626162306663373633653638636332
      37663034663362643334393034656366393464376661613565323839383832363133386662316666
      34366434626662333432

  nextcloud:
    redirect_uris:
      - "https://nextcloud.{{ common_tld }}/apps/oidc_login/oidc"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64356331393331343364313138363839326437653463343337363065383762333439643132346330
      6135636263353134316166636566313764663261653436660a663430333338346461653536316231
      62643566376233333830333666323337343034626434643438333230643463643238303637363839
      3565383866343533660a343134663561343534386137373233316532366263343134663361336430
      38346166303633613962666361333130666630306262383966393261663036383862333631326132
      30376133303539616635323735656665646361333131396339376364333537616635376365656633
      32343936376237663731306530356638323331333365653538323334396235353064376433336639
      31356237373666326435

  opengist:
    redirect_uris:
      - https://opengist.{{ common_tld }}/oauth/openid-connect/callback
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36373533616662633237393238346165393230393635666664336434343438343463353436663635
      3634643838323536653430613636313962333233376434320a363235383462646130323439373564
      32666335323231623066363034646433336165303034363238316263623337313531656233653537
      3435353135663831380a363365663632366666656530643436663531656566623437346565646366
      31366462623764313865383962303861333636306637363733353965646364623232323538643766
      63663338356130653831343463326431396664363761323065626566613363633131363863383837
      34636139363764626463313266636336303262666265373438343263623061646438306464646664
      65396638366462616465

  otf:
    redirect_uris:
      - https://otf.{{ common_tld }}/oauth/{{ oidc_provider }}/callback
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64663963646630333465323230346162343839633834346133646132623661626461356438633135
      3765366633663230616563636436303064376639333461620a636537363964373264386463393564
      63333765323037343663323165636637626332366634643665333735363965326639323536636135
      3739613638616136360a383461363335386461646665663537383837646265313839366665623563
      39323966616266666130613135393234316535396638323136343837353065323366656638633035
      38383362363530386562613232323838366637333239363965313431646431666162653735303034
      30373831626138666436343364663333663564346134323536663134306337643835633563636237
      66383762633933303530

  outline:
    redirect_uris:
      - "https://outline.{{ common_tld }}/auth/oidc.callback"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      64363766363566363030353362626165303263336336393433376438613031633633626231383565
      3133613761363764616332646439663132303563313537390a383934343037346634353761303936
      38323439336331346265636337633734666263383966626436656330656161353034343533306132
      3239333561383666330a393464616433396439616465623766343331356430386365633431323236
      30643862623636393635386231393136306536373237363132323734383135653830353261323862
      35316138303737353932353130613631303431376465323835646266643430343063356263623435
      62316634383434366234653462386333626433643061373264366633623365653931303865346339
      38646162393964353231

  paperless:
    redirect_uris:
      - "https://paperless.{{ common_tld }}/accounts/oidc/authelia/login/callback/"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35336431613763353161306133313837626638376263633462353431353065653530623665313931
      6538636238383932366661663061316266353836353034340a613339636332373863383963313365
      34333535373961383766623234396632323031633737363563303662656465396331383161663662
      6335346661386438330a653139373333353331373836373761653631343433393435356265346531
      32636264386666356361373364373332633236306161626431303138353064303531363263633632
      63663138333833366236316235346232326463343139633532663063393762346634626337636138
      33663066663133663963383031346261653262323934336663373933653266653766623532643864
      35313430636361383635

  portainer:
    redirect_uris:
      - "https://portainer.{{ common_tld }}"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      66383435363165323965623431373534363733356638303464323737663665633632383763353237
      6261643538613438346431343037346130366132636561380a633963643632346339366133386638
      39646266343032313165356665333664333431386438623838306339363333333330376666393362
      6464336562326265300a653662346233633066323366373434306233613365623431643337663033
      66356432613233393064363539303062623661356635333663633463643366656235323830313334
      37623438323832636563636661383639333639316239363262346563646136306237653534373262
      66316133656138626435633139396666323537386131383538343265623234303737353434323062
      61613132613264653836

  stirlingpdf:
    redirect_uris:
      - "https://stirlingpdf.{{ common_tld }}/login/oauth2/code/oidc"
    secret: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39316137306631643361373730653361633561653234343666353561386265303832336638613838
      6437386538326435633134326535613165353365616630640a336665376461646339386366373864
      37386665366337373061366132653939643565373065626630656335306337353635303038363462
      6434623439306634610a633466313939373062303938633434653038393762616663646439643264
      31356561666534333164653961303565316338393438366536633730393664373765313264393561
      62663731373036656663353534373633373538333762303036383637393665346136623437346634
      64393632353533303061366432326237303838386461343266646464626532353437386264353831
      66356165343639666338
