---

shlink_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37343163633065613738663030373165316235363565613234643230386664393963346465663764
  6536386531353336393064363462633339636661373962380a633339623439636238646164396336
  33316430393737653634663666636634363061626363613161333266353137323835373963646431
  6530373335303839360a613061303436383764326335653037643762646631376264316362373765
  61653531306565316335666135343535616638636136393834646263623432663231653962316565
  6264346532653063633463643966613931396534346638336133

shlink_domain: "s.{{ common_tld }}"
