---

traefik_certresolver: letsencrypt

traefik_bypass_auth_header:
  key: x-bypass-auth
  value: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    39663966356137656535363032376236313064396339646335333033363063306236346362396365
    3230326663333130366231646432633866643932353866350a343466626164373937396534373363
    35663338383637373930313539313961643364316162663939656163353364326362376636643866
    3166306262303038330a663366653766663135306530333238613364376162336461643138616130
    33353566303762313364666237333339633733613266333335643862326136353533346161336438
    65353038623733323866303234636633303665306531666432653330316131323563343237653335
    37366235383130376132653933303833306162373935653730656233653137626466363634626262
    35303166383434323737

traefik_middleware_forward_auth: authelia@docker
# can't replace authelia until https://github.com/goauthentik/authentik/issues/6886 is resolved
# traefik_middleware_forward_auth: authentik@docker
