---
galaxy_info:
  author: calvinbui
  description: BookStackApp
  company: https://calvin.me
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - bookstack
    - wiki
dependencies: []
