---

influxdb_directory: "{{ config_directory }}/influxdb"

influxdb_name: "{{ application }}-influxdb"
influxdb_username: "{{ application }}"
influxdb_password: "changeme"
# influxdb_token:
influxdb_org: "{{ application }}-org"
influxdb_bucket: "{{ application }}-bucket"

influxdb_traefik:
  enable: false
influxdb_homepage:
  enable: false
